# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3f1b2c32472767affd28a856a1095c78ffa5eefee2187a4e153f709edae361b293bf92e8d18bffe76a50a7ec768fa812fdadd0fe9fe6b16d3b5e5a422c6965

test:
  secret_key_base: ba405237c2b6452d49a38ff5482740e55872c670cc07ddbd374d1cea0e4b7b38ff41df37063ebc6ceef9ebd10d9d67f8fa4f88c3774990fadee6388dc46430d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
